name: Feature 
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Changes
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# LATEST REPO UPDATES" >> report.md
          cml-send-comment report.md
